In [5]:
import numpy as np

X=np.array([[1,0,1,0],[1,1,0,1],[1,0,0,1]])

y=np.array([[1],[1],[0]])

def sigmoid(x):
    return 1/(1+np.exp(-x))
def derivative(x):
    return x*(1-x)


epoch=5000
lr=0.1

hidden_layer_neuron=3
input_layer=X.shape[1]
output_layer=1;

#first weight matrix

w1=np.random.uniform(size=(input_layer,hidden_layer_neuron))
b1=np.random.uniform(size=(1,hidden_layer_neuron))


w2=np.random.uniform(size=(hidden_layer_neuron,1))
b2=np.random.uniform(size=(1,output_layer))

In [6]:
for i in range(0,epoch):
    #forward propagation
    transfer=np.dot(X,w1)+b1
    activation=sigmoid(transfer)
    
    transfer_output=np.dot(activation,w2)+b2
    output=sigmoid(transfer_output)
    
    #Back-Propagation
    E=y-output
    error_at_output=E*derivative(output)
    w2=w2+activation.T.dot(error_at_output)*lr
    b2=b2+np.sum(error_at_output,axis=0,keepdims=True)*lr
    
    error_at_hidden=error_at_output.dot(w2.T)*derivative(activation)
    w1=w1+X.T.dot(error_at_hidden)*lr
    b1=b2+np.sum(error_at_hidden,axis=0,keepdims=True)*lr
    
    
    
    

In [10]:
 #Back-Propagation
E=y-output
error_at_output=E*derivative(output)
w2=w2+activation.T.dot(error_at_output)*lr
b2=b2+np.sum(error_at_output,axis=0,keepdims=True)*lr
    
error_at_hidden=error_at_output.dot(w2.T)*derivative(activation)
print(error_at_hidden)
w1=w1+np.dot(X,error_at_hidden)*lr
b1=b2+np.sum(error_at_hidden,axis=0,keepdims=True)*lr

[[ 0.00061249 -0.00030148 -0.00023279]
 [ 0.00193525 -0.00079788 -0.00123615]
 [-0.00242023  0.00107545  0.00148374]]


ValueError: shapes (3,4) and (3,3) not aligned: 4 (dim 1) != 3 (dim 0)